### Crear una categoría
POST http://127.0.0.1:8000/categorias
Content-Type: application/json

{
  "nombre": "Bebidas sin alcohol"
}

### Listar todas las categorías
GET http://127.0.0.1:8000/categorias

### Actualizar una categoría (suponiendo id=1)
PUT http://127.0.0.1:8000/categorias/1
Content-Type: application/json

{
  "nombre": "Bebidas con alcohol"
}
