@url = http://localhost:8000

###GET 
GET {{url}}/usuarios
Accept: application/json


###POST

POST {{url}}/usuarios
Content-Type: application/json
Accept: application/json

{
  "nombre": "Santino Pilot",
  "username": "FutbolBoy10",
  "contrasena": "elMejorJugador"
}

###PUT

PUT {{url}}/usuarios/1
Content-Type: application/json
Accept: application/json

{
  "nombre": "Juan Chiplote Modificado",
  "username": "JuanitoMod123",
  "contrasena": "dificilMod123"
}

###DELETE

DELETE {{url}}/usuarios/3
Accept: application/json
